apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-helloworld
  name: golang-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: golang-helloworld
  template:
    metadata:
      labels:
        deployment: golang-helloworld
    spec:
      containers:
      - name: golang-helloworld
        image: b0rr3g0/golang-hello-world:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
